
name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Install backend dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          else
            echo "No backend package.json found, skipping backend dependencies"
          fi
        working-directory: ./backend

      - name: Deploy with Wrangler (with aider retry logic)
        id: deploy_attempt
        continue-on-error: true
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./backend
          command: deploy --config wrangler.jsonc

      - name: aider-chat-action for deploy fixes
        if: always()
        uses: mirrajabi/aider-github-action@v1.1.0
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: |
            The deployed Workers AI application at workersai.hacolby.workers.dev has JavaScript runtime errors:
            Error: ae@https://workersai.hacolby.workers.dev/assets/chat-C_adMHAj.js:2:60621
            
            This appears to be a frontend build issue causing chat functionality to fail. Please:
            1. Check frontend build configuration for Workers compatibility
            2. Verify compatibility_flags in wrangler.jsonc include nodejs_compat
            3. Fix any ES module or bundling issues in the chat component
            4. Ensure proper error handling in the worker code
            5. Check for missing dependencies or incorrect imports
            
            Fix the JavaScript runtime error and ensure the chat functionality works properly.
          max-retries: 10
          auto-commit: true
          commit-message: "Fix JavaScript runtime errors in chat functionality (attempt ${{ github.run_attempt }})"

      - name: Retry deployment after aider fixes
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./backend
          command: deploy --config wrangler.jsonc
