name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Remove cache: npm since no root lock file exists

      - name: Install frontend dependencies with fallback
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "Using pnpm (lock file found)"
            npx pnpm install
          else
            echo "Falling back to npm (no pnpm lock file)"
            npm install
          fi
        working-directory: ./frontend

      - name: Build frontend with fallback
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            npx pnpm build
          else
            npm run build
          fi
        working-directory: ./frontend

      - name: Install backend dependencies with fallback
        run: |
          if [ -f "package.json" ]; then
            if [ -f "pnpm-lock.yaml" ]; then
              echo "Using pnpm for backend"
              npx pnpm install
            else
              echo "Using npm for backend"
              npm install
            fi
          else
            echo "No backend package.json found, skipping backend dependencies"
          fi
        working-directory: ./backend

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./backend
          command: deploy --config wrangler.jsonc
